[project]
name = "graphix-pyzx"
version = "0.1.0"
description = "Graphix plugin for importing and exporting XZ-diagrams with pyzx"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["graphix>=0.3.5", "pyzx>=0.10"]

[project.optional-dependencies]
dev = [
    "nox>=2026.4.10",
    "types-networkx>=3.6.1.20260518",
]

[tool.mypy]
# Keep in sync with pyright
files = ["graphix_pyzx", "tests"]
strict = true

[tool.pyright]
# Keep in sync with mypy
include = ["graphix_pyzx", "tests"]
reportUnknownArgumentType = "information"
reportUnknownLambdaType = "information"
reportUnknownMemberType = "information"
reportUnknownParameterType = "information"
reportUnknownVariableType = "information"
# reportInvalidTypeVarUse is a warning by default
reportInvalidTypeVarUse = "error"
